import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const terminologySidebars: SidebarsConfig = {
  terminologySidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default terminologySidebars;
